# Data Generation

This notebook generates a synthetic customer churn dataset for a UK-based SaaS company.

The generated dataset includes customer demographics, subscription details, product usage metrics, customer support interactions, engagement indicators, revenue metrics, and churn information.

# Step 1: Basic Dataset

In [41]:
import pandas as pd
import numpy as np

np.random.seed(42)

n_rows = 15000

df = pd.DataFrame()

df["customer_id"] = [f"CF{i:05d}" for i in range(1, n_rows + 1)]

df["region"] = np.random.choice(
    [
        "London",
        "South East",
        "South West",
        "East Midlands",
        "West Midlands",
        "North East",
        "North West",
        "Scotland",
        "Wales"
    ],
    n_rows
)

df["subscription_plan"] = np.random.choice(
    ["Starter", "Professional", "Enterprise"],
    n_rows,
    p=[0.5, 0.35, 0.15]
)

df["contract_type"] = np.random.choice(
    ["Monthly", "Annual"],
    n_rows,
    p=[0.7, 0.3]
)

df["tenure_months"] = np.random.exponential(
    scale=18,
    size=n_rows
).astype(int) + 1

df["monthly_logins"] = np.random.poisson(
    lam=45,
    size=n_rows
)

df["customer_satisfaction_score"] = np.random.randint(
    1,
    11,
    n_rows
)

# Industry
df["industry"] = np.random.choice(
    [
        "Retail",
        "Finance",
        "Healthcare",
        "Education",
        "Logistics",
        "Technology",
        "Manufacturing"
    ],
    n_rows
)

# Company Size
df["company_size"] = np.random.choice(
    [
        "Micro",
        "Small",
        "Medium",
        "Large"
    ],
    n_rows,
    p=[0.4, 0.35, 0.2, 0.05]
)



# Years in Business
df["years_in_business"] = np.random.randint(
    1,
    31,
    n_rows
)

# Monthly Subscription Fee
df["monthly_subscription_fee_gbp"] = np.random.choice(
    [29, 79, 199],
    n_rows,
    p=[0.5, 0.35, 0.15]
)

# Discount Percentage
df["discount_percentage"] = np.random.randint(
    0,
    41,
    n_rows
)

# Employee Count

employee_count = []

for size in df["company_size"]:

    if size == "Micro":
        employee_count.append(
            np.random.randint(1,11)
        )

    elif size == "Small":
        employee_count.append(
            np.random.randint(11,51)
        )

    elif size == "Medium":
        employee_count.append(
            np.random.randint(51,251)
        )

    else:
        employee_count.append(
            np.random.randint(251,1001)
        )

df["employee_count"] = employee_count

# Active Users
df["active_users"] = (
    df["employee_count"]
    * np.random.uniform(0.2, 0.8, n_rows)
).astype(int)

# Feature Usage Score
df["feature_usage_score"] = np.random.randint(
    1,
    101,
    n_rows
)

# Average Session Duration
df["avg_session_duration_minutes"] = np.random.randint(
    5,
    180,
    n_rows
)

# Projects Created
df["projects_created"] = np.random.randint(
    0,
    200,
    n_rows
)

# Integrations Enabled
df["integrations_enabled"] = np.random.randint(
    0,
    20,
    n_rows
)

# Support Tickets
df["support_tickets_last_6m"] = np.random.poisson(
    2,
    n_rows
)

# Resolution Time
df["avg_resolution_time_hours"] = np.random.randint(
    1,
    72,
    n_rows
)

# Payment Failures
df["payment_failures_last_12m"] = np.random.randint(
    0,
    6,
    n_rows
)

# Email Open Rate
df["email_open_rate"] = np.random.randint(
    0,
    101,
    n_rows
)

df.loc[
    df["subscription_plan"] == "Starter",
    "email_open_rate"
] = np.where(
    np.random.rand(
        len(df[df["subscription_plan"] == "Starter"])
    ) < 0.08,
    np.nan,
    df.loc[
        df["subscription_plan"] == "Starter",
        "email_open_rate"
    ]
)

# Webinar Attendance
df["webinar_attendance_count"] = np.random.randint(
    0,
    12,
    n_rows
)

# Monthly Recurring Revenue
df["monthly_recurring_revenue"] = (
    df["monthly_subscription_fee_gbp"]
    * np.random.uniform(0.8, 1.2, n_rows)
).round(2)

# Lifetime Value
df["lifetime_value"] = (
    df["monthly_recurring_revenue"]
    * df["tenure_months"]
).round(2)

churn_score = (
    (df["tenure_months"] < 6).astype(int)
    + (df["monthly_logins"] < 20).astype(int)
    + (df["customer_satisfaction_score"] < 5).astype(int)
    + (df["payment_failures_last_12m"] > 2).astype(int)
    + (df["contract_type"] == "Monthly").astype(int)
    + (df["feature_usage_score"] < 30).astype(int)
    + (df["support_tickets_last_6m"] > 5).astype(int)
)

df["signup_date"] = pd.to_datetime(
    np.random.choice(
        pd.date_range("2020-01-01", "2025-06-01"),
        len(df)
    )
)

df["last_login_date"] = (
    df["signup_date"]
    + pd.to_timedelta(
        np.random.randint(
            1,
            365,
            len(df)
        ),
        unit="D"
    )
)

today = pd.Timestamp("2025-06-20")

df["last_login_date"] = np.where(
    df["last_login_date"] > today,
    today,
    df["last_login_date"]
)

df["last_login_date"] = pd.to_datetime(
    df["last_login_date"]
)

df["customer_segment"] = np.random.choice(
    ["SMB", "Mid-Market", "Enterprise"],
    len(df),
    p=[0.6, 0.3, 0.1]
)

df["acquisition_channel"] = np.random.choice(
    [
        "Organic Search",
        "Google Ads",
        "LinkedIn",
        "Referral",
        "Direct",
        "Partner"
    ],
    len(df)
)

df["churn"] = np.where(
    churn_score >= 3,
    "Yes",
    "No"
)
df.head()

,customer_id,region,subscription_plan,contract_type,tenure_months,monthly_logins,customer_satisfaction_score,industry,company_size,years_in_business,...,payment_failures_last_12m,email_open_rate,webinar_attendance_count,monthly_recurring_revenue,lifetime_value,signup_date,last_login_date,customer_segment,acquisition_channel,churn
0,CF00001,North West,Professional,Monthly,3,42,2,Technology,Medium,30,...,0,96.0,3,92.24,276.72,2024-12-27,2025-06-20,SMB,LinkedIn,Yes
1,CF00002,East Midlands,Starter,Monthly,1,45,7,Retail,Small,15,...,2,33.0,1,75.62,75.62,2022-11-11,2023-03-06,SMB,LinkedIn,Yes
2,CF00003,Scotland,Starter,Monthly,14,59,4,Healthcare,Small,3,...,2,90.0,7,72.83,1019.62,2023-05-01,2023-10-18,SMB,Partner,Yes
3,CF00004,West Midlands,Professional,Annual,16,48,7,Logistics,Small,1,...,2,79.0,10,74.76,1196.16,2025-04-01,2025-05-17,Mid-Market,Organic Search,No
4,CF00005,North West,Professional,Monthly,1,50,10,Education,Micro,15,...,2,0.0,1,29.92,29.92,2021-09-04,2022-02-05,Enterprise,Partner,No

In [42]:
df.columns.tolist()

['customer_id',
 'region',
 'subscription_plan',
 'contract_type',
 'tenure_months',
 'monthly_logins',
 'customer_satisfaction_score',
 'industry',
 'company_size',
 'years_in_business',
 'monthly_subscription_fee_gbp',
 'discount_percentage',
 'employee_count',
 'active_users',
 'feature_usage_score',
 'avg_session_duration_minutes',
 'projects_created',
 'integrations_enabled',
 'support_tickets_last_6m',
 'avg_resolution_time_hours',
 'payment_failures_last_12m',
 'email_open_rate',
 'webinar_attendance_count',
 'monthly_recurring_revenue',
 'lifetime_value',
 'signup_date',
 'last_login_date',
 'customer_segment',
 'acquisition_channel',
 'churn']

In [43]:
df.shape

(15000, 30)

In [44]:
(df["last_login_date"] < df["signup_date"]).sum()

np.int64(0)

In [45]:
df["churn"].value_counts()

churn
No     9586
Yes    5414
Name: count, dtype: int64

# Imbalance the dataset by randomly converting some churned customers to retained

In [70]:
yes_idx = df[df["churn"] == "Yes"].index

# randomly convert 1500 churned customers to retained
change_idx = np.random.choice(
    yes_idx,
    1500,
    replace=False
)

df.loc[change_idx, "churn"] = "No"

In [71]:
df["churn"].value_counts()

churn
No     14315
Yes      985
Name: count, dtype: int64

In [72]:
df["churn"].value_counts(normalize=True) * 100

churn
No     93.562092
Yes     6.437908
Name: proportion, dtype: float64

# Step 2: Introduce Missing Values

In [74]:
cols_with_missing = [
    "monthly_logins",
    "feature_usage_score",
    "customer_satisfaction_score",
    "email_open_rate",
    "avg_session_duration_minutes"
]

for col in cols_with_missing:

    missing_idx = np.random.choice(
        df.index,
        size=int(len(df) * 0.05),
        replace=False
    )

    df.loc[missing_idx, col] = np.nan

In [75]:
df.isnull().sum()

customer_id                        0
region                             0
subscription_plan                  0
contract_type                      0
tenure_months                      0
monthly_logins                  2191
customer_satisfaction_score     2170
industry                           0
company_size                       0
years_in_business                  0
monthly_subscription_fee_gbp       0
discount_percentage                0
employee_count                     0
active_users                       0
feature_usage_score             2195
avg_session_duration_minutes    2181
projects_created                   0
integrations_enabled               0
support_tickets_last_6m            0
avg_resolution_time_hours          0
payment_failures_last_12m          0
email_open_rate                 2677
webinar_attendance_count           0
monthly_recurring_revenue          0
lifetime_value                     0
signup_date                        0
last_login_date                    0
customer_segment                   0
acquisition_channel                0
churn                              0
dtype: int64

# Step 3: Duplicates

In [76]:
duplicates = df.sample(
    frac=0.02,
    random_state=42
)

df = pd.concat(
    [df, duplicates],
    ignore_index=True
)

In [77]:
print(df.shape)
print(df.duplicated().sum())

(15606, 30)
408

# Step 4: Add Inconsistent Categories

In [80]:
# London variations
idx = df[df["region"] == "London"].sample(
    300,
    random_state=42
).index

df.loc[idx[:100], "region"] = "london"
df.loc[idx[100:200], "region"] = "LONDON"
df.loc[idx[200:], "region"] = " London "


# Scotland variations
idx = df[df["region"] == "Scotland"].sample(
    150,
    random_state=43
).index

df.loc[idx[:50], "region"] = "scotland"
df.loc[idx[50:100], "region"] = "SCOTLAND"
df.loc[idx[100:], "region"] = " Scotland "


# Wales variations
idx = df[df["region"] == "Wales"].sample(
    150,
    random_state=44
).index

df.loc[idx[:50], "region"] = "wales"
df.loc[idx[50:100], "region"] = "WALES"
df.loc[idx[100:], "region"] = " Wales "


# South East variations
idx = df[df["region"] == "South East"].sample(
    150,
    random_state=45
).index

df.loc[idx[:50], "region"] = "south east"
df.loc[idx[50:100], "region"] = "SOUTH EAST"
df.loc[idx[100:], "region"] = " South East "

In [81]:
df["region"].value_counts()

region
North West       1761
North East       1759
East Midlands    1739
South West       1731
West Midlands    1709
Scotland         1588
Wales            1552
South East       1543
London            868
 London           304
london            302
LONDON            300
south east         50
 Wales             50
SOUTH EAST         50
scotland           50
wales              50
 South East        50
SCOTLAND           50
 Scotland          50
WALES              50
Name: count, dtype: int64

# Step 5: Outliers

In [83]:
outlier_idx = np.random.choice(
    df.index,
    150,
    replace=False
)

df.loc[
    outlier_idx,
    "monthly_logins"
] = np.random.randint(
    1000,
    5000,
    150
)

In [84]:
df["monthly_logins"].describe()

count    13428.000000
mean       142.263405
std        569.498972
min         21.000000
25%         41.000000
50%         45.000000
75%         50.000000
max       4999.000000
Name: monthly_logins, dtype: float64

In [85]:
df["monthly_logins"].sort_values(
    ascending=False
).head(10)

14453    4999.0
14331    4974.0
7652     4969.0
2169     4968.0
8315     4944.0
3283     4936.0
12592    4935.0
2435     4927.0
6263     4925.0
7849     4921.0
Name: monthly_logins, dtype: float64

# Step 6: Invalid Values

In [86]:
invalid_idx = np.random.choice(
    df.index,
    50,
    replace=False
)

df.loc[
    invalid_idx,
    "customer_satisfaction_score"
] = 15

In [87]:
invalid_idx = np.random.choice(
    df.index,
    30,
    replace=False
)

df.loc[
    invalid_idx,
    "tenure_months"
] = -5

In [89]:
print(
    df[df["customer_satisfaction_score"] > 10].shape
)

print(
    df[df["tenure_months"] < 0].shape
)

(98, 30)
(59, 30)

# Step 7: Save Raw Dataset

In [90]:
import os

os.makedirs("data", exist_ok=True)

In [91]:
df.to_csv(
    "data/raw_data.csv",
    index=False
)

print("Dataset Saved Successfully")

Dataset Saved Successfully

In [92]:
df.shape

(15606, 30)

In [93]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15606 entries, 0 to 15605
Data columns (total 30 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customer_id                   15606 non-null  str
 1   region                        15606 non-null  str
 2   subscription_plan             15606 non-null  str
 3   contract_type                 15606 non-null  str
 4   tenure_months                 15606 non-null  int64
 5   monthly_logins                13428 non-null  float64
 6   customer_satisfaction_score   13403 non-null  float64
 7   industry                      15606 non-null  str
 8   company_size                  15606 non-null  str
 9   years_in_business             15606 non-null  int32
 10  monthly_subscription_fee_gbp  15606 non-null  int64
 11  discount_percentage           15606 non-null  int32
 12  employee_count                15606 non-null  int64
 13  active_users                  15606 non-null  int64
 14  feature_usage_score           13364 non-null  float64
 15  avg_session_duration_minutes  13386 non-null  float64
 16  projects_created              15606 non-null  int32
 17  integrations_enabled          15606 non-null  int32
 18  support_tickets_last_6m       15606 non-null  int32
 19  avg_resolution_time_hours     15606 non-null  int32
 20  payment_failures_last_12m     15606 non-null  int32
 21  email_open_rate               12872 non-null  float64
 22  webinar_attendance_count      15606 non-null  int32
 23  monthly_recurring_revenue     15606 non-null  float64
 24  lifetime_value                15606 non-null  float64
 25  signup_date                   15606 non-null  datetime64[us]
 26  last_login_date               15606 non-null  datetime64[us]
 27  customer_segment              15606 non-null  str
 28  acquisition_channel           15606 non-null  str
 29  churn                         15606 non-null  str
dtypes: datetime64[us](2), float64(7), int32(8), int64(4), str(9)
memory usage: 3.1 MB

In [94]:
df.describe()

,tenure_months,monthly_logins,customer_satisfaction_score,years_in_business,monthly_subscription_fee_gbp,discount_percentage,employee_count,active_users,feature_usage_score,avg_session_duration_minutes,...,integrations_enabled,support_tickets_last_6m,avg_resolution_time_hours,payment_failures_last_12m,email_open_rate,webinar_attendance_count,monthly_recurring_revenue,lifetime_value,signup_date,last_login_date
count,15606.000000,13428.000000,13403.000000,15606.000000,15606.000000,15606.000000,15606.000000,15606.000000,13364.000000,13386.000000,...,15606.000000,15606.000000,15606.000000,15606.000000,12872.000000,15606.000000,15606.000000,15606.00000,15606,15606
mean,18.342945,142.263405,5.563083,15.455145,72.043701,20.013649,72.055235,35.391965,50.470368,92.241670,...,9.619441,2.009227,36.028963,2.521658,49.763285,5.485454,72.006664,1332.35286,2022-09-08 20:42:15.640138,2023-03-01 18:33:26.920415
min,-5.000000,21.000000,1.000000,1.000000,29.000000,0.000000,1.000000,0.000000,1.000000,5.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,23.200000,23.21000,2020-01-01 00:00:00,2020-01-06 00:00:00
25%,6.000000,41.000000,3.000000,8.000000,29.000000,10.000000,7.000000,2.000000,25.000000,48.000000,...,5.000000,1.000000,18.000000,1.000000,24.000000,2.000000,28.950000,259.60000,2021-05-01 00:00:00,2021-10-31 06:00:00
50%,13.000000,45.000000,6.000000,16.000000,29.000000,20.000000,21.000000,9.000000,50.000000,92.000000,...,10.000000,2.000000,36.000000,3.000000,50.000000,5.000000,34.720000,655.49000,2022-09-13 00:00:00,2023-03-13 00:00:00
75%,25.000000,50.000000,8.000000,23.000000,79.000000,30.000000,50.000000,29.000000,75.000000,136.000000,...,15.000000,3.000000,54.000000,4.000000,75.000000,9.000000,85.280000,1526.25250,2024-01-07 00:00:00,2024-07-06 00:00:00
max,189.000000,4999.000000,15.000000,30.000000,199.000000,40.000000,998.000000,762.000000,100.000000,179.000000,...,19.000000,11.000000,71.000000,5.000000,100.000000,11.000000,238.770000,32841.20000,2025-06-01 00:00:00,2025-06-20 00:00:00
std,17.869419,569.498972,2.981481,8.674889,58.199859,11.821708,144.220165,76.514871,28.929879,50.850686,...,5.785966,1.423487,20.447570,1.703121,29.277326,3.458068,59.383009,1979.70520,NaN,NaN

In [95]:
print(df.columns.tolist())

['customer_id', 'region', 'subscription_plan', 'contract_type', 'tenure_months', 'monthly_logins', 'customer_satisfaction_score', 'industry', 'company_size', 'years_in_business', 'monthly_subscription_fee_gbp', 'discount_percentage', 'employee_count', 'active_users', 'feature_usage_score', 'avg_session_duration_minutes', 'projects_created', 'integrations_enabled', 'support_tickets_last_6m', 'avg_resolution_time_hours', 'payment_failures_last_12m', 'email_open_rate', 'webinar_attendance_count', 'monthly_recurring_revenue', 'lifetime_value', 'signup_date', 'last_login_date', 'customer_segment', 'acquisition_channel', 'churn']